DROP TABLE IF EXISTS Student;  
CREATE TABLE Student (  
id INT AUTO_INCREMENT  PRIMARY KEY,  
firstname VARCHAR(50) NOT NULL,  
lastname VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
age INT(8) NOT NULL
);  